default:
  dividend:
    rate_of_equity: 10
    rate_of_debt: 10
    marginal_tax_rate: 30
  risk_free:
    rate: 6

# Different websites and their relevant information

moneycontrol:
  stock_details:
    prefix: "https://www.moneycontrol.com/mccode/common/autosuggestion_solr.php?classic=true&query="
    postfix: "&type=1&format=json"

  financials:
    prefix: "https://www.moneycontrol.com/financials/"
    outstanding_shares:
      suffix: "/capital-structure/"

  stock_price:
    prefix: "https://www.moneycontrol.com/india/stockpricequote/"

trendlyne:
  stock_details:
    full_url: "https://trendlyne.com/member/api/ac_snames/stock/?term="

  dividend:
    full_url: "https://trendlyne.com/equity/Dividend/"
      
investing:
  t_bill_91:
    full_url: "https://in.investing.com/instruments/HistoricalDataAjax"
