default:
  rate_of_equity: 10
  rate_of_debt: 10
  marginal_tax_rate: 30
  risk_free_rate: 6
  source_file: "/resources/stocks.xlsx"
  target_path: "/resources/stock_metadata.csv"
  individual_stock_path: "/resources/stocks/"
  json_target_path: "/resources/stock_metadata.json"

# Different websites and their relevant information

moneycontrol:
  stock_details:
    prefix: "https://www.moneycontrol.com/mccode/common/autosuggestion_solr.php?classic=true&query="
    postfix: "&type=1&format=json"

  financial_statements:
    prefix: "https://www.moneycontrol.com/financials/"
    outstanding_shares:
      suffix: "/capital-structure/"
    balance_sheet: "/balance-sheetVI/"
    cash_flow_statement: "/cash-flowVI/"
    income_statement: "/profit-lossVI/"
    financial_ratios: "/ratiosVI/"

  stock_price:
    prefix: "https://www.moneycontrol.com/india/stockpricequote/"

trendlyne:
  stock_details:
    full_url: "https://trendlyne.com/member/api/ac_snames/stock/?term="

  dividend:
    full_url: "https://trendlyne.com/equity/Dividend/"
      
investing:
  t_bill_91:
    full_url: "https://in.investing.com/instruments/HistoricalDataAjax"
  nifty_50:
    full_url: "https://in.investing.com/indices/s-p-cnx-nifty-historical-data"

nse_india:
  base_url: "https://www.nseindia.com"
  base_stock_details: "/get-quotes/equity?symbol="
  stock_details: "/api/quote-equity?symbol="
  stock_historical_data: "/api/historical/cm/equity?symbol="
  stock_historical_data_download: "/api/historical/cm/equity?symbol="
  market_capital_suffix: "&section=trade_info"


